# Generated by Django 3.0.7 on 2020-06-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200626_0445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
